insert into internships
  (title, company, description, field, city, work_mode, stipend_min, stipend_max, stipend_note, duration, apply_url, source, posted_at)
values
  (
    'Frontend Developer Intern',
    'PixelForge Technologies',
    'Work with our web team to build and ship UI features using React and Tailwind CSS. You''ll pair with senior engineers on real product work.',
    'Software Development',
    'Bangalore',
    'Hybrid',
    15000,
    25000,
    null,
    '3 months',
    'https://example.com/apply/pixelforge-frontend',
    'Internshala',
    '2026-09-18T09:00:00.000Z'
  ),
  (
    'Backend Developer Intern',
    'CodeStream Labs',
    'Help build and maintain REST APIs powering our core product. You''ll work with Node.js, PostgreSQL, and get exposure to production deployments.',
    'Software Development',
    'Remote',
    'Remote',
    20000,
    30000,
    null,
    '6 months',
    'https://example.com/apply/codestream-backend',
    'Instahyre',
    '2026-09-21T09:00:00.000Z'
  ),
  (
    'Digital Marketing Intern',
    'BrandWave Media',
    'Assist in planning and running social media campaigns for client brands, track ad performance, and help write campaign reports.',
    'Marketing',
    'Chennai',
    'On-site',
    8000,
    12000,
    null,
    '3 months',
    'https://example.com/apply/brandwave-marketing',
    'Naukri Campus',
    '2026-09-15T09:00:00.000Z'
  ),
  (
    'UI/UX Design Intern',
    'Studio Loop',
    'Design wireframes and high-fidelity mockups for mobile and web products, and help run basic usability tests with real users.',
    'Design',
    'Pune',
    'Hybrid',
    10000,
    10000,
    'Performance-based bonus',
    '4 months',
    'https://example.com/apply/studioloop-design',
    'AngelList',
    '2026-09-20T09:00:00.000Z'
  ),
  (
    'Data Analyst Intern',
    'Quantify Analytics',
    'Clean and analyze datasets, build dashboards in Excel/SQL, and present findings to the analytics team on a weekly basis.',
    'Data Science',
    'Bangalore',
    'On-site',
    18000,
    22000,
    null,
    '3 months',
    'https://example.com/apply/quantify-data-analyst',
    'Internshala',
    '2026-09-22T09:00:00.000Z'
  ),
  (
    'Content Writing Intern',
    'BrightPage Media',
    'Research and write blog articles, social captions, and newsletters for early-stage startups.',
    'Content Writing',
    'Remote',
    'Remote',
    0,
    0,
    'Certificate + letter of recommendation',
    '2 months',
    'https://example.com/apply/brightpage-content',
    'Naukri Campus',
    '2026-09-20T09:00:00.000Z'
  ),
  (
    'Finance & Accounts Intern',
    'LedgerWorks Consulting',
    'Support the finance team with bookkeeping, invoice reconciliation, and preparing basic financial statements.',
    'Finance',
    'Chennai',
    'On-site',
    12000,
    12000,
    null,
    '3 months',
    'https://example.com/apply/ledgerworks-finance',
    'Company Website',
    '2026-09-12T09:00:00.000Z'
  ),
  (
    'Business Development Intern',
    'NextGen Ventures',
    'Research potential partners, assist with outreach campaigns, and help prepare pitch decks for client meetings.',
    'Business Development',
    'Pune',
    'Hybrid',
    10000,
    15000,
    null,
    '4 months',
    'https://example.com/apply/nextgen-bizdev',
    'Internshala',
    '2026-09-23T09:00:00.000Z'
  );
