import { Internship } from "./types";

export const fakeInternships: Internship[] = [
  {
    id: "1",
    title: "Frontend Developer Intern",
    company: "PixelForge Technologies",
    description:
      "Work with our web team to build and ship UI features using React and Tailwind CSS. You'll pair with senior engineers on real product work.",
    field: "Software Development",
    city: "Bangalore",
    work_mode: "Hybrid",
    stipend_min: 15000,
    stipend_max: 25000,
    stipend_note: null,
    duration: "3 months",
    apply_url: "https://example.com/apply/pixelforge-frontend",
    source: "Internshala",
    posted_at: "2026-09-18T09:00:00.000Z",
    created_at: "2026-09-18T09:00:00.000Z",
  },
  {
    id: "2",
    title: "Backend Developer Intern",
    company: "CodeStream Labs",
    description:
      "Help build and maintain REST APIs powering our core product. You'll work with Node.js, PostgreSQL, and get exposure to production deployments.",
    field: "Software Development",
    city: "Remote",
    work_mode: "Remote",
    stipend_min: 20000,
    stipend_max: 30000,
    stipend_note: null,
    duration: "6 months",
    apply_url: "https://example.com/apply/codestream-backend",
    source: "Instahyre",
    posted_at: "2026-09-21T09:00:00.000Z",
    created_at: "2026-09-21T09:00:00.000Z",
  },
  {
    id: "3",
    title: "Digital Marketing Intern",
    company: "BrandWave Media",
    description:
      "Assist in planning and running social media campaigns for client brands, track ad performance, and help write campaign reports.",
    field: "Marketing",
    city: "Chennai",
    work_mode: "On-site",
    stipend_min: 8000,
    stipend_max: 12000,
    stipend_note: null,
    duration: "3 months",
    apply_url: "https://example.com/apply/brandwave-marketing",
    source: "Naukri Campus",
    posted_at: "2026-09-15T09:00:00.000Z",
    created_at: "2026-09-15T09:00:00.000Z",
  },
  {
    id: "4",
    title: "UI/UX Design Intern",
    company: "Studio Loop",
    description:
      "Design wireframes and high-fidelity mockups for mobile and web products, and help run basic usability tests with real users.",
    field: "Design",
    city: "Pune",
    work_mode: "Hybrid",
    stipend_min: 10000,
    stipend_max: 10000,
    stipend_note: "Performance-based bonus",
    duration: "4 months",
    apply_url: "https://example.com/apply/studioloop-design",
    source: "AngelList",
    posted_at: "2026-09-20T09:00:00.000Z",
    created_at: "2026-09-20T09:00:00.000Z",
  },
  {
    id: "5",
    title: "Data Analyst Intern",
    company: "Quantify Analytics",
    description:
      "Clean and analyze datasets, build dashboards in Excel/SQL, and present findings to the analytics team on a weekly basis.",
    field: "Data Science",
    city: "Bangalore",
    work_mode: "On-site",
    stipend_min: 18000,
    stipend_max: 22000,
    stipend_note: null,
    duration: "3 months",
    apply_url: "https://example.com/apply/quantify-data-analyst",
    source: "Internshala",
    posted_at: "2026-09-22T09:00:00.000Z",
    created_at: "2026-09-22T09:00:00.000Z",
  },
  {
    id: "6",
    title: "Content Writing Intern",
    company: "BrightPage Media",
    description:
      "Research and write blog articles, social captions, and newsletters for early-stage startups.",
    field: "Content Writing",
    city: "Remote",
    work_mode: "Remote",
    stipend_min: 0,
    stipend_max: 0,
    stipend_note: "Certificate + letter of recommendation",
    duration: "2 months",
    apply_url: "https://example.com/apply/brightpage-content",
    source: "Naukri Campus",
    posted_at: "2026-09-20T09:00:00.000Z",
    created_at: "2026-09-20T09:00:00.000Z",
  },
  {
    id: "7",
    title: "Finance & Accounts Intern",
    company: "LedgerWorks Consulting",
    description:
      "Support the finance team with bookkeeping, invoice reconciliation, and preparing basic financial statements.",
    field: "Finance",
    city: "Chennai",
    work_mode: "On-site",
    stipend_min: 12000,
    stipend_max: 12000,
    stipend_note: null,
    duration: "3 months",
    apply_url: "https://example.com/apply/ledgerworks-finance",
    source: "Company Website",
    posted_at: "2026-09-12T09:00:00.000Z",
    created_at: "2026-09-12T09:00:00.000Z",
  },
  {
    id: "8",
    title: "Business Development Intern",
    company: "NextGen Ventures",
    description:
      "Research potential partners, assist with outreach campaigns, and help prepare pitch decks for client meetings.",
    field: "Business Development",
    city: "Pune",
    work_mode: "Hybrid",
    stipend_min: 10000,
    stipend_max: 15000,
    stipend_note: null,
    duration: "4 months",
    apply_url: "https://example.com/apply/nextgen-bizdev",
    source: "Internshala",
    posted_at: "2026-09-23T09:00:00.000Z",
    created_at: "2026-09-23T09:00:00.000Z",
  },
];
